name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: he0119/setup-python@main
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: poetry install

      - name: Run tests
        run: poetry run pytest --cov=src --cov-report xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
